apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: db-dev
  labels:
    app: postgres
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: hp@root
  POSTGRES_DB: k8s_db
