apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/path/ggs/minio/data"
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Retain
