version : "3.7"

services:
  app:
    image: ggowthamsankar/reference_api:latest
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://db:4307/test_school_new?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: secret
    depends_on:
      - db
  db:
    image: mariadb
    environment:
      DATABASE_HOST: localhost
      MYSQL_DATABASE: test_school_new
      MYSQL_USER: admin
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - \\\wsl$\docker-desktop-data\version-pack-data\community\docker\volumes\shared_data\\_data
    ports:
      - 4307:3306